name: Repo Sync to Gitee

on:
  # push:             # main分支提交代码即触发
  #   branches:
  #     - main
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '5 0 * * *'

env:
  # 仓库名称
  REPO_NAME: ${{ github.event.repository.name }}
  GITHUB_REPO: cmontage/mas-cn
  GITEE_REPO: cmontage/mas-cn

jobs:
  # 同步代码仓库
  mirror-to-gitee:
    name: 同步代码到Gitee
    runs-on: ubuntu-latest

    steps:
      - name: 配置Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: 同步到Gitee
        uses: abersheeran/sync-gitee-mirror@v1-beta
        with:
          repository: cmontage/${{ env.REPO_NAME }}
          username: cmontage
          password: ${{ secrets.GITEE_PASSWORD }}